function PlotExtraGraphSignalAnalysis(vSig, vSigRecPhi, vSigRecV, vSigRecRep, vSigRef, vSigInt, vSigNys, vSigRep, vSigCoeffsPhi, vSigCoeffsV, vSigRefCoeffsPhi)

n = size(vSig);
N = size(vSigRef);

PlotGraphSignalAnalysis(vSig, vSigRecPhi, vSigRecV, vSigRef, vSigInt, vSigNys, ...
    vSigCoeffsPhi, vSigCoeffsV, vSigRefCoeffsPhi);

PlotGraphSignalErrors([], [1, n], vSig, {vSigRecPhi, vSigRecV, vSigRecRep}, ...
    {'|s-s_{\Phi}^{{\bf rec}}|', '|s-s_{V}^{{\bf rec}}|', '|s-s_{{\bf K}}^{{\bf rec}}|'},  ...
    'Projection error ($n$ given nodes)')
if n+1 < N
    PlotGraphSignalErrors([], [n+1, N], vSigRef(n+1:N), ...
        {vSigInt(n+1:N), vSigNys(n+1:N), vSigRep(n+1:N)}, ...
        {'|s^{{\bf ref}}-s^{{\bf int}}|', '|s^{{\bf ref}}-s^{{\bf nys}}|', '|s^{{\bf ref}}-s^{{\bf rep}}|'},  ...
        'Interpolation error ($N-n$ nodes)')
end

PlotGraphSignalErrors([], [1, N], vSigRef, {vSigInt, vSigNys, vSigRep}, ...
    {'|s^{{\bf ref}}-s^{{\bf int}}|', '|s^{{\bf ref}}-s^{{\bf nys}}|', '|s^{{\bf ref}}-s^{{\bf rep}}|'},  ...
    'Total error ($N$ nodes)')
end