function figTitle = GetInterpFigTitle(dim, omegaTilde, sigmaTilde, muTilde)
if dim == 3
    figTitle = ['Eigenfunctions of $\tilde{{\bf W}}$ on the entire plane' newline ...
        '$\tilde{\omega}$ = ' num2str(omegaTilde, '%.2f') ...
        '; $\tilde{\Sigma} =  \left[ {\matrix{ ',num2str(sigmaTilde(1,1)),' & ',  num2str(sigmaTilde(1,2)),' & ',  num2str(sigmaTilde(1,3)),...
        ' \cr ', num2str(sigmaTilde(2,1)) , ' &  ',  num2str(sigmaTilde(2,2)),' & ',  num2str(sigmaTilde(2,3)),...
        ' \cr ', num2str(sigmaTilde(3,1)) , ' &  ',  num2str(sigmaTilde(3,2)),' & ',  num2str(sigmaTilde(3,3)),' } }  \right]$', ...
        '; $\tilde{\mu} =  \left[ {\matrix{ ',num2str(muTilde(1)), ...
        ' \cr ', num2str(muTilde(3)), ...
        ' \cr ', num2str(muTilde(2)),' } }  \right]$' ];
elseif dim == 2
    figTitle = ['Eigenfunctions of $\tilde{{\bf W}}$ on the entire plane' newline ...
        '$\tilde{\omega}$ = ' num2str(omegaTilde, '%.2f') ...
        '; $\tilde{\Sigma} =  \left[ {\matrix{ ',num2str(sigmaTilde(1,1)),' & ',  num2str(sigmaTilde(1,2)),...
        ' \cr ', num2str(sigmaTilde(2,1)) , ' &  ',  num2str(sigmaTilde(2,2)),' } }  \right]$', ...
        '; $\tilde{\mu} =  \left[ {\matrix{ ',num2str(muTilde(1)), ...
        ' \cr ', num2str(muTilde(2)),' } }  \right]$' ];
elseif dim == 1
    figTitle = ['Eigenfunctions of $\tilde{{\bf W}}$ on the entire axis' newline ...
    '$\tilde{\omega}$ = ' num2str(omegaTilde, '%.2f') ...
    '; $\tilde{\sigma}$ = ' num2str(sigmaTilde, '%.2f') ...
    '; $\tilde{\mu}$ = ' num2str(muTilde, '%.2f') ];
end

end