function PlotExtraGraphSignalAnalysis(vSig, vSigRecPhi, vSigRecV, vSigRecRep, vSigRef, vSigInt, vSigNys, vSigRep, vSigCoeffsPhi, vSigCoeffsV, vSigRefCoeffsPhi)

n = size(vSig);
N = size(vSigRef);

PlotGraphSignalAnalysis(vSig, vSigRecPhi, vSigRecV, vSigRef, vSigInt, vSigNys, ...
    vSigCoeffsPhi, vSigCoeffsV, vSigRefCoeffsPhi);

PlotGraphSignalErrors([], [1, n], vSig, {vSigRecPhi, vSigRecV, vSigRecRep}, ...
    {'|s-s^{{\bf RoMix}}|', '|s-s^{{\bf nys}}|', '|s-s^{{\bf rep}}|'},  ...
    'Projection error ($n$ given nodes)')
if n+1 < N
    PlotGraphSignalErrors([], [n+1, N], vSigRef(n+1:N), ...
        {vSigInt(n+1:N), vSigNys(n+1:N), vSigRep(n+1:N)}, ...
        {'|\tilde{s}-\tilde{s}^{{\bf RoMix}}|', '|\tilde{s}-\tilde{s}^{{\bf nys}}|', '|\tilde{s}-\tilde{s}^{{\bf rep}}|'},  ...
        'Interpolation error ($N-n$ nodes)')
end

PlotGraphSignalErrors([], [1, N], vSigRef, {vSigInt, vSigNys, vSigRep}, ...
    {'|\tilde{s}-\tilde{s}^{{\bf RoMix}}|', '|\tilde{s}-\tilde{s}^{{\bf nys}}|', '|\tilde{s}-\tilde{s}^{{\bf rep}}|'},  ...
    'Total error ($N$ nodes)')
end